---
title: "Research Proposal"
---

**Due <u>October 1</u> on Blackboard**

- Length: 300-400 words
- Format: 12pt Times New Roman, Double-Spaced

Imagine you have all the necessary resources to conduct an empirical research study of some hypothetical causal relationship. Propose one specific research question and the methods you believe would be neecssary to to study it.

Your proposal will need to include paragraphs describing at least the following:

1. The motivation for your project. Why is it important to study this topic? Has this particular study been done before? (do a search for literature on this topic)
2. The design of the empirical study you would undertake. How would you conduct it? What choices would you make, given what you know of research design? What aspects of the phenomenon in question limit your design?
3. The possible outcomes, and what we could do with this new empirical knowledge. What do you expect and why? What evidence might come up that would be counter to your expectations? For each possible outcome, what would it mean to obtain this result?

You are encouraged to seek preliminary feedback before submission. Email your teaching fellow or attend office hours before September 28.
