project:
  type: website

website:
  title: "Introduction to Experimental Design"
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true
  sidebar:
    style: floating
    border: true
    contents:
      - section: Introduction
        contents: Introduction/*
  navbar:
    background: dark
    left:
    - text: Home
      href: "index.qmd"
    - text: Announcements
      href: "https://learn.bu.edu/ultra/courses/_261733_1/announcements"
      target: _blank
    - text: Grades
      href: "https://learn.bu.edu/ultra/courses/_261733_1/grades"
      target: _blank
  search:
    location: navbar
    type: textbox
    copy-button: true
    show-item-context: true
  # announcement: 
  #   icon: info-circle
  #   dismissable: true
  #   content: "e.g. 'Homework 2 has been rescheduled'"
  #   type: info
  #   position: below-navbar
  page-footer: |
    Copyright &copy; 2025 The Authors.
    Licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>
    <img class="cc-icon" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg">
    <img class="cc-icon" src="https://mirrors.creativecommons.org/presskit/icons/by.svg">
    <img class="cc-icon" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg">
    <img class="cc-icon" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg">

format:
  html:
    theme:
      light: united
      dark: solar
    css: styles.css
    toc: true
    date-format: full
    published-title: Lecture Date
