project:
  type: website

website:
  title: "Introduction to Experimental Design"
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true
  draft-mode: gone
  favicon: assets/favicon.svg
  sidebar:
    style: floating
    border: true
    contents:
      - section: 1. Introduction
        contents: Introduction/*
      - section: 2. Research Design
        contents: Design/*
      - section: Labs
        contents: Labs/*
      - Slides.qmd
      - text: "Syllabus for Fall 2025"
        href: syllabus.qmd

  navbar:
    background: dark
    left:
    - text: Home
      href: "index.qmd"
    - text: Syllabus
      href: "syllabus.qmd"
    - text: Announcements
      href: "https://learn.bu.edu/ultra/courses/_261733_1/announcements"
      target: _blank
    - text: Grades
      href: "https://learn.bu.edu/ultra/courses/_261733_1/grades"
      target: _blank
  search:
    location: navbar
    type: textbox
    copy-button: true
    show-item-context: true
  announcement: 
    icon: info-circle
    dismissable: true
    content: "The course syllabus has been updated."
    type: light
    position: above-navbar
  page-footer: |
    Copyright &copy; 2025 The Authors.
    Licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>
    <img class="cc-icon" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg">
    <img class="cc-icon" src="https://mirrors.creativecommons.org/presskit/icons/by.svg">
    <img class="cc-icon" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg">
    <img class="cc-icon" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg">

format:
  html:
    theme:
      light: united
      dark: solar
    css: styles.css
    toc: true
    date-format: full
    published-title: Lecture Date
    highlight-style:
      light: gruvbox
      dark: github
    code-block-border-left: true
    code-block-bg: true
    code-copy: false