---
title: Handling Confounds
subtitle: Summary of Lecture 6
date: 2025-09-15
---

:::{.callout-note}
The [research proposal](/Projects/Project01.qmd) project is upcoming. Review the associated lecture slides for details.
:::

<!-- :::{.text-muted .small}
[Click here](https://learn.bu.edu/ultra/courses/_261733_1/outline/file/_16576997_1) to download the corresponding lecture slides.
:::

--- -->

## Confounding Variables

When we are analyzing causal relationships, a **confound** is a variable that influences _both_ the independent and dependent variable, creating a misleading _association_.

Say, hypothetically, that a positive association is found between coffee and lung cancer. That there is a positive association means that those who drink coffee are likely to have had lung cancer, and those who have had lung cancer are likely to drink coffee. To speculate, it might seem like the causal direction is from coffee to lung cancer. It could turn out, however, that those who drink coffee are _also_ likely to smoke.

In this example, _smoking_ is a confound: a spurious relationship, which can lead us to make a false inference. Confounds can sometimes mask real causal realtionships.

Here's another example: Based on observations, hormone-replacement therapy seemed to prevent heart disease in women.

```{dot}
//| fig-height: 1.5
//| fig-width: 4
//| fig-cap: "A _causal graph_ shows the hypothesized causal relationships. Here it's a _negative_ relationship that was theorized: H.R.T. prevents heart disease."
digraph Confounder {
  graph [rankdir=LR];
  node [shape=ellipse, style=filled, fillcolor=white];
  "HRT" -> "Heart Disease" [ label="?" ]
}
```

Later randomized controlled trials revealed that this effect disappeared after controlling for confounds of socioeconomic status and education.

```{dot}
//| fig-height: 2
//| fig-width: 4
//| fig-cap: "Being of higher SES and education meant that, separately, women were more likely to seek out and afford H.R.T. and they were also less liklely to get heart disease."
digraph Confounder {
  graph [rankdir=LR];
  node [shape=ellipse, style=filled, fillcolor=white];
  "SES & Education" -> "H.R.T";
  "SES & Education" -> "Heart Disease";
}
```

Consider this one: A childs birth-order is related to down syndrome, with risk increasing for each child.

```{dot}
//| fig-height: 2
//| fig-width: 4
//| fig-cap: "Down syndrome seems to be causally related to birth order."
digraph Confounder {
  graph [rankdir=LR];
  node [shape=ellipse, style=filled, fillcolor=white];
  "Birth Order" -> "Down Syndrome" [ label="?" ];
}
```



<details>
<summary>
Think for a moment and then click here to reveal an explanation. Is there any other variable which could be at play here?
</summary>


As it turns out, _age of the mother_, which can only increase with number of children, was the common denominator.

```{dot}
//| fig-height: 2
//| fig-width: 4
//| fig-cap: "Down syndrome seems to be causally related to birth order."
digraph Confounder {
  graph [rankdir=LR];
  node [shape=ellipse, style=filled, fillcolor=white];
  "Mother's Age" -> "Down Syndrome";
  "Mother's Age" -> "Birth Order";
}
```
</details>

## Extraneous Variables

Those variables that affect the _dependent variable_ are **extraneous**. While confounding variables are extraneous, not all extraneous variables are confounders.

- A genetic predisposition to lung cancer is an extraneous variable, because it does affect lung cancer but does not affect smoking.

:::{.aside}
With a genetic predisposition, might person might know that their parent or grandparent developed lung cancer? The individual predisposed to lung cancer might therefore purposely avoid smoking. Thus, it's _possible_ that there _is_ a relationship between genetic predisposition and smoking, though not considered here.
:::

```{dot}
//| fig-height: 1
//| fig-width: 3
//| fig-align: center
digraph Extraneous {
  graph [rankdir=LR];
  node [shape=ellipse, style=filled, fillcolor=white];
  "Genetic Predisposition" -> "Lung Cancer" [label="risk"];
  "Smoking" -> "Lung Cancer" [label="risk"]
}
```

- Age is a confound for both smoking and lung cancer (consider that in the U.S. you cannot purchase tobacco under the age of 21).
```{dot}
//| fig-height: 1
//| fig-width: 3
//| fig-align: center
digraph Confound {
graph [rankdir=LR];
node [shape=ellipse, style=filled, fillcolor=white];
"Age" -> "Smoking" [label="legal ability"];
"Age" -> "Lung Cancer" [label="risk"];
"Smoking" -> "Lung Cancer" [label="risk"]
}
```

## Confounds in Non-Experimental Research

In non-experimental research, the independent variable is not being randomly assigned and is therefore likely to be related to confounds. There are ways to control these confounds, however, even without random assignment.

:::{.aside}
There are limits to what we can control - notably, we can only control for known and measured confounders.
:::

Were we comparing smokers and non-smokers, we could control the effect of _age_ by **matching** every individual in the smoker group to an individual in the non-smoker group. By comparing _pairs_ we avoid the confounding effect of age.

Alternatively, we could restrict our anlaysis to a **subgroup**, such as by only looking at smoking rates in the 40-45 age range. Because age is effectively held constant, it is controlled. We can **stratify** our sample by intentionally selecting subgroups of particular composition for analysis.

Lastly, we can use **statistical control** to subtract the estimated effect of a confound from the total effect observed. We will see more on this later in the semester.




## Experimental Confounds

We learned previously that _random assignment_ protects against both known and unknown confounds because, effectively, confounders are distributed equally across conditions.  This is true, however, only in **expectation**  (i.e. samples approaching infinity). Due to chance, confounds _can_ be a concern in any given sample, especially if the sample is small.

:::{.aside}
Consider flipping a coin ten times, the _expectation_ is five heads and five tails. That is, with a fair coin on average it will come out to 50-50. In any given sample, however, even with 1000 flips there is still the unlikely possibility that 1000 heads could come up.
:::

Consider an experiment investigating a causal relationship of coffee consumption on exam scores. If we randomly assign participants to drink a specific number of cups of coffee per day, then _number of cups_ is **decoupled** from extraneous variables, right? Can't we then attribute any difference in _test-score_ to how many cups of coffee they drink?

```{dot}
//| fig-height: 1
//| fig-width: 3
//| fig-align: center
//| fig-cap: At first pass, it seems this causal relationship has been effectively isolated by the experiment design.
digraph Confound {
graph [rankdir=LR];
node [shape=ellipse, style=filled, fillcolor=white];
"Daily Caffeine Intake" -> "Test Score";
}
```

A potential confound like _sleep duration_ could still throw a wrench in the design. With little sleep, people may consume more caffeine. We controlled for this by assigning _number of cups_. We did not account for, however, that sleep duration can also be decreased by caffeine consumption or caffeine withdrawal.

```{dot}
//| fig-height: 1
//| fig-width: 3
//| fig-align: center
//| fig-cap: Even in randomized experiments, it is possible for confounds to be lurking.
digraph Confound {
graph [rankdir=LR];
node [shape=ellipse, style=filled, fillcolor=white];
"Sleep Duration" -> "Caffeine Intake";
"Caffeine Intake" -> "Sleep Duration";
"Sleep Duration" -> "Test Score";
"Caffeine Intake" -> "Test Score";
}
```

Of course, because random assignment is only truly decoupling in expectation, we still might consider the rare event that those assigned to one group happen to be those who already sleep more.

The techniques listed above for non-experimental research still apply. Therefore, we could use matching or stratification to ensure sleep duration is controlled for (e.g. include only participants who sleep seven hours). Alternatively, we could use a **within-subjects** design such that we observe the effects of all conditions in every participant over time.